/**
 * @file app.config.ts
 * @description Per-game visual identity. Generated by tools/propagate-theme.js.
 * Edit the source script and re-run to update.
 */
export const APP_CONFIG = {
  name: "Solitaire",
  primary: "#14B8A6",
  secondary: "#0F766E",
  splash: {
    glow: "rgba(15,118,110,0.6)",
    sallyGlow: "rgba(20,184,166,0.8)",
    pillBorder: "rgba(20,184,166,0.5)",
    pillBg: "rgba(15,118,110,0.15)",
    pillText: "#CCFBF1",
    suit: "♠",
    suit2: "♦",
  },
  slides: {
    slide2: { tint: ["rgba(20,184,166,0.55)","rgba(15,118,110,0.7)","rgba(6,30,28,0.95)"], variant: "spread" },
    slide3: { tint: ["rgba(45,212,191,0.45)","rgba(19,78,74,0.85)","rgba(6,30,28,0.95)"], variant: "fan" },
    slide4: { tint: ["rgba(245,158,11,0.45)","rgba(20,184,166,0.7)","rgba(6,30,28,0.95)"], variant: "grid" },
  },
} as const;

export type SlideVariant = 'fan' | 'scattered' | 'spread' | 'grid';
